<?php

namespace CarRentBundle\Repository;

/**
 * OrderCarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderCarRepository extends \Doctrine\ORM\EntityRepository
{
}
